export const sortOrder: Record<string, number> = {
  "langgraph-python": 10,
  "langgraph-typescript": 11,
  "langgraph-fastapi": 12,

  "google-adk": 30,
  "ms-agent-python": 31,
  "maf-python": 31,
  "ms-agent-dotnet": 32,
  "maf-dotnet": 32,
  strands: 33,
  "aws-fast-langgraph": 34,
  "aws-fast-strands": 35,

  mastra: 60,
  "crewai-crews": 61,
  crewai: 61,
  "pydantic-ai": 63,
  "claude-sdk-python": 64,
  "claude-sdk-typescript": 65,
  agno: 66,
  ag2: 67,
  llamaindex: 68,
  langroid: 69,
  "spring-ai": 70,
  "deep-agents": 71,
  "oracle-open-agent-spec": 72,
  "openai-agents-sdk": 73,

  "built-in-agent": 900,
  n8n: 910,
  cloudflare: 920,
};
